#!/bin/sh

set -eu

python3 -m CoverageTestRunner --ignore-missing-from=without-tests yarns vmdb
pylint3 --rcfile pylint.conf vmdb
yarn \
    --shell=python2 \
    --shell-arg '' \
    --shell-library yarns/lib.py \
    --env "PYTHONPATH=$(pwd)/yarns" \
    --cd-datadir \
    yarns/*.yarn "$@"
