#!/bin/sh

set -eu

output="$1"
shift

pandoc  -H vmdb2.css\
        --smart \
        --toc \
        --chapters \
        --number-sections \
	--standalone \
        --self-contained \
        -o "$output" "$@"
